# Generated by Django 5.1.1 on 2024-10-09 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(300)])),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity_for_sale', models.IntegerField()),
                ('is_for_sale', models.BooleanField(default=True)),
                ('medium', models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('digital_art', 'Digital Art'), ('photography', 'Photography'), ('mixed_media', 'Mixed Media'), ('printmaking', 'Printmaking'), ('ceramics', 'Ceramics'), ('textile', 'Textile Art')], max_length=30)),
                ('material', models.CharField(max_length=50)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in cm', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
            ],
        ),
    ]
