# Generated by Django 5.1.1 on 2024-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='viewed_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='viewed_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
