# Generated by Django 5.1.1 on 2024-10-09 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(700)]),
        ),
    ]
