# Generated by Django 5.1.1 on 2024-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='artist_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='collector_address',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
            preserve_default=False,
        ),
    ]
