# Generated by Django 5.1.1 on 2024-10-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_artist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='postcode',
            field=models.CharField(default='SE15 4JR', max_length=255),
            preserve_default=False,
        ),
    ]
